spring.application.name=Donor-service
server.port=8081
eureka.client.service-url.defaultZone:http://localhost:8761/eureka
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#SYSTEM_JWT_TOKEN= eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbnUiLCJVc2VyX1Bob25lTnVtYmVyICI6Ijk4NzY1MTMyMTMiLCJVc2VyX1JvbGU6IjpbIlVTRVIiLCJET05PUiIsIlVTRVIiLCJVU0VSIiwiQURNSU4iLCJET05PUiIsIlVTRVIiXSwiSld0X1VzZXJJZCA6IjoiMSIsImlhdCI6MTc1ODQ0MDA1NiwiZXhwIjoxNzU4NDc2MDU2fQ.IjVsLP2sBc-KYrK58ZSYyitWF-P-CfnbSZZuf_KRPeM